# Arquivo de configuracao padrao do webserv
server {
    listen              8080;
    server_name         localhost;

    client_max_body_size 1M;

    error_page          400 /errors/400.html;
    error_page          403 /errors/403.html;
    error_page          404 /errors/404.html;
    error_page          405 /errors/405.html;
    error_page          408 /errors/408.html;
    error_page          411 /errors/411.html;
    error_page          413 /errors/413.html;
    error_page          414 /errors/414.html;
    error_page          431 /errors/431.html;
    error_page          500 /errors/500.html;
    error_page          501 /errors/501.html;
    error_page          502 /errors/502.html;
    error_page          503 /errors/503.html;
    error_page          504 /errors/504.html;
    error_page          505 /errors/505.html;

    location / {
        root            www;
        index           index.html;
        methods         GET;
        autoindex       off;
    }

    location /errors {
        root            www;
        methods         GET;
    }

    location /files {
        root            www;
        methods         GET;
        autoindex       on;
    }

    location /private {
        root            www;
        methods         GET;
        autoindex       off;
    }

    location /upload {
        root            www;
        methods         GET POST DELETE;
        upload_store    www/upload;
        autoindex       on;
    }

    location /cgi-bin {
        root            www;
        methods         GET POST;
        cgi             .py;
    }
}